# Generated by Django 3.2.12 on 2022-06-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersofcomp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compusers',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersofcomp.usersrole', verbose_name='Позиция'),
        ),
    ]
